<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.0 Transitional//EN'>
<html>
<head>
    <title>
        <?php echo $this->dados->getCedente()->getIdentificacao(); ?>
    </title>
    <meta http-equiv=Content-Type content=text/html charset=utf-8/>
    <meta name="Generator" content="Projeto BoletoPHP - www.boletophp.com.br - Licença GPL"/>
    <style type=text/css>
        .cp {
            font: 10px Arial;
            color: black
        }

        .ti {
            font: 9px Arial, Helvetica, sans-serif
        }

        .ld {
            font: bold 15px Arial;
            color: #000000
        }

        .ct {
            FONT: bold 9px "Arial Narrow";
            COLOR: #000000
        }

        .cn {
            FONT: 9px Arial;
            COLOR: black
        }

        .ld2 {
            font: bold 12px Arial;
            color: #000000
        }

        td[align='right'] {
            padding-right: 1px;
        }

        .sem-espacamento {
            line-height: 0px;
        }

        @media print {
            .no-print {
                display: none;
            }
        }
    </style>
</head>

<body text=#000000 bgColor=#ffffff topMargin=0 rightMargin=0>
<table cellspacing=0 cellpadding=0 width=666 border=0>
    <tbody>
    <tr>
        <td class=cp width=300 style="font: bold 14px Arial;">
            <?php echo $this->dados->getBanco()->getNomeBanco() ?>
        </td>
        <td class=cp width=70 align="right" style="font: bold 10px Arial;">
            Recibo do Pagador
        </td>
    </tr>
    </tbody>
</table>

<tbody>
<tr>
    <td colspan="5">
        <img height="1"
             src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg=="
             width="666" border="0">
    </td>
</tr>
</tbody>


<table cellspacing=0 cellpadding=0 border=0>
    <tbody>
    <tr>
        <td class=ct valign=top width=7 height=13>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=ct valign=top width=324 height=13>Beneficiário</td>

        <td class=ct valign=top width=7 height=13>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=ct valign=top align="center" width=160 height=13>Nosso Número</td>

        <td class=ct valign=top width=7 height=13>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=ct valign=top width=160 height=13>Vencimento</td>

        <td class=ct valign=top width=7 height=13>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
    </tr>
    <tr>
        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=cp valign=top width=324 height=12>
            <span class="campo">
                <?php echo $this->dados->getCedente()->getNomeCedente() . " - " . $this->dados->getCedente()->getDocumento(); ?>
            </span>
        </td>
        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC 
                 width=1 border=0>
        </td>

        <td class=cp valign=top align="center" width=160 height=12>
            <span class="campo">
                <?php echo str_pad($this->dados->getBoleto()->getNossoNumero(),9,0,STR_PAD_LEFT) ?>
            </span>
        </td>
        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=cp valign=top align="center" width=160 height=12>
            <span class="campo">
                <?php echo ($this->dados->getBoleto()->getDataVencimento())
                    ? $this->dados->getBoleto()->getDataVencimento()->format("d/m/Y")
                    : "Contra Apresentação" ?>
            </span>
        </td>
        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
    </tr>

    <tr>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top width=324 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=324 border=0>
        </td>

        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top width=160 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=160 border=0>
        </td>

        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top width=160 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=160 border=0>
        </td>
    </tr>
    </tbody>
</table>


<table cellspacing=0 cellpadding=0 border=0>
    <tbody>
    <tr>
        <td class=ct valign=top width=7 height=13>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=ct valign=top width=100 height=13>Data do Docto</td>

        <td class=ct valign=top width=7 height=13>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=ct valign=top align="center" width=110 height=13>Número do Documento</td>

        <td class=ct valign=top width=7 height=13>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=ct valign=top align="center" width=100 height=13>Carteira</td>

        <td class=ct valign=top width=7 height=13>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=ct valign=top align="center" width=160 height=13>Agência/Código Beneficiário</td>

        <td class=ct valign=top width=7 height=13>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=ct valign=top width=160 height=13>Valor</td>

        <td class=ct valign=top width=7 height=13>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
    </tr>

    <tr>
        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=cp valign=top width="100" height=12>
            <span class="campo">
                <?php echo $this->dados->getBoleto()->getDataDocumento()->format("d/m/Y") ?>
            </span>
        </td>

        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=cp valign=top align="center" width=110 height=12>
            <span class="campo">
                <?php echo $this->dados->getBoleto()->getNumeroDocumento() ?>
            </span>
        </td>

        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=cp valign=top align="center" width=100 height=12>
            <span class="campo">
                <?php echo $this->dados->getCedente()->getCarteira() ?>
            </span>
        </td>

        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=cp valign=top align=center width=160 height=12>
            <span class="campo">
                <?php echo $this->dados->getCedente()->getAgencia().' / '.$this->dados->getCedente()->getContaCedente() ?>
            </span>
        </td>

        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=cp valign=top align=center width=160 height=12>
            <span class="campo">
                <?php echo number_format($this->dados->getBoleto()->getValor() / 100, 2, ",", ".") ?>
            </span>
        </td>


        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
    </tr>

    <tr>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top width=100 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=100 border=0>
        </td>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top width=110 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=110 border=0>
        </td>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top width=100 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=100 border=0>
        </td>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top width=160 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=160 border=0>
        </td>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top width=160 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=160 border=0>
        </td>
    </tr>
    </tbody>
</table>


<!--PAGADOR-->
<table cellspacing=0 cellpadding=0 border=0>
    <tbody>
    <tr>
        <td class=ct valign=top width=7 height=12>
            <img height=15
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=ct valign=top width=658 height=13>Pagador</td>

        <td class=ct valign=top width=7 height=12>
            <img height=15
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
    </tr>

    <tr>
        <td class=cp valign=top width=7 height=15>
            <img height=15
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=cp valign=top width=658 height=15>
            <span class="campo">
                <?php echo $this->dados->getSacado()->getNome() . ' - ' . $this->dados->getSacado()->getDocumento() ?>
            </span>
        </td>

        <td class=ct valign=top width=7 height=15>
            <img height=15
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
    </tr>

    <tr>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top width=658 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=658 border=0>
        </td>
    </tr>
    </tbody>
</table>
<!--PAGADOR-->


<!--INSTRUÇÕES-->
<table cellspacing=0 cellpadding=0 border=0>
    <tbody>
    <tr>
        <td class=ct valign=top width=7 height=15>
            <img height=15
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=ct valign=top colspan=3 width=658 height=15>Instruções (Todas as informações deste bloqueto são de
            exclusiva responsabilidade do Beneficiário)
        </td>

        <td class=ct valign=top width=7 height=15>
            <img height=15
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
    </tr>

    <tr>
        <td class=ct valign=top width=7 height=20>
            <img height=20
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=ct valign=top colspan=3 width=658 height=20>
            <span class="campo">* ESTE BOLETO REPRESENTA DUPLICATA CEDIDA FIDUCIARIAMENTE AO BANCO SAFRA S/A, FICANDO VEDADO O PAGAMENTO DE QUALQUER OUTRA FORMA QUE NÃO ATRAVÉS DO PRESENTE BOLETO.</span><br>
        </td>

        <td class=ct valign=top width=7 height=20>
            <img height=20
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
    </tr>

    <tr>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>

        <td valign=top width=658 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=658 border=0>
        </td>
    </tr>
    </tbody>
</table>
<!--INSTRUÇÕES-->


<table cellspacing=0 cellpadding=0 width=666 border=0>
    <tbody>
    <tr>
        <td width=7>
        </td>
        <td width=500 class=cp>
            <br>
        </td>
        <td width=159>
        </td>
    </tr>
    </tbody>
</table>


<!--LINHA PONTILHADA-->
<table cellspacing=0 cellpadding=0 width=666 border=0>
    <tr>
        <td class=ct width=666>
        </td>
    </tr>
    <tbody>
    <tr>
        <td class=ct width=666>
            <img height=1
                 src=data:ïmage/png;base64,iVBORw0KGgoAAAANSUhEUgAAApkAAAACAQAAAAA76vpWAAAAGUlEQVR42mNgbDiQYCDBw8ZMPUYDAy0MBQCvGyXfT4/GUQAAAABJRU5ErkJggg==
                 width=665 border=0>
        </td>
    </tr>
    </tbody>
</table>
<br>
<!--LINHA PONTILHADA-->


<table cellspacing=0 cellpadding=0 width=666 border=0>
    <tr>
        <td class=cp width=150 valign="bottom">
            <span class="campo" style="font: bold 14px Arial;">
                <?php echo $this->dados->getBanco()->getNomeBanco() ?>
            </span>
        </td>

        <td class=cpt width=58 valign=bottom>
            <div align=center>
                <font class=bc>
                    <?php echo $this->dados->getBanco()->getCodigoBanco(), '-', $this->dados->getBanco()->getCodigoBancoDv() ?>
                </font>
            </div>
        </td>
        <td width=3 valign=bottom>
            <img height=22
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAATAQMAAACA8k5ZAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=2 border=0>
        </td>
        <td class=ld align=right width=453 valign=bottom>
                    <span class=ld> 
                        <span class="campotitulo">
                            <img src="<?php echo $this->dados->getBoleto()->getLinhaDigitavel('base64')->render() ?>"/>
                        </span>
                    </span>
        </td>
    </tr>
    <tbody>
    <tr>
        <td colspan=5>
            <img height=2
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=666 border=0>
        </td>
    </tr>
    </tbody>
</table>
<table cellspacing=0 cellpadding=0 border=0>
    <tbody>
    <tr>
        <td class=ct valign=top width=7 height=13>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
        <td class=ct valign=top width=472 height=13>Local de pagamento</td>
        <td class=ct valign=top width=7 height=13>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=ct valign=top width=178 height=13>Vencimento</td>

        <td class="cp" valign="top" width="7" height="13">
            <img height="13" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width="1" border="0">
        </td>
    </tr>
    <tr>
        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
        <td class=cp valign=top width=472 height=12>
            Pagável em qualquer Banco do Sistema de Compensação
            <!--Até o vencimento pagável em qualquer banco. Após o vencimento, apenas nas agências do Banco Safra.-->
        </td>
        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=cp valign=bottom align=right width=178 height=12>
                        <span class="campo">
                            <?php echo ($this->dados->getBoleto()->getDataVencimento())
                                ? $this->dados->getBoleto()->getDataVencimento()->format("d/m/Y")
                                : "Contra Apresentação" ?>
                        </span>
        </td>

        <td class="cp" valign="top" width="7" height="12">
            <img height="12" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width="1" border="0">
        </td>
    </tr>
    <tr>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top width=472 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=472 border=0>
        </td>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top width=179 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=179 border=0>
        </td>
    </tr>
    </tbody>
</table>

<table cellspacing=0 cellpadding=0 border=0>
    <tbody>
    <tr>
        <td class=ct valign=top width=7 height=13>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=ct valign=top width=472 height=13>Beneficiário</td>
        <td class=ct valign=top width=7 height=13>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=ct valign=top width=178 height=13>Agência/Código Beneficiário</td>

        <td class="cp" valign="top" width="7" height="13">
            <img height="13" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width="1" border="0">
        </td>
    </tr>
    <tr>
        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
        <td class=cp valign=top width=0 height=12>
                        <span class="campo">
                            <?php echo $this->dados->getCedente()->getNomeCedente() . " - " . $this->dados->getCedente()->getDocumento() ?>
                        </span>
        </td>
        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=cp valign=top align=right width=178 height=12>
            <span class="campo">
                <?php echo $this->dados->getCedente()->getAgencia().' / '.$this->dados->getCedente()->getContaCedente() ?>
            </span>
        </td>

        <td class="cp" valign="top" width="7" height="12">
            <img height="12" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width="1" border="0">
        </td>
    </tr>
    <tr>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=472 border=0>
        </td>
        <td valign=top height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=179 border=0>
        </td>
    </tr>
    </tbody>
</table>


<table cellspacing=0 cellpadding=0 border=0>
    <tbody>
    <tr>
        <td class=ct valign=top width=7 height=13>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
        <td class=ct valign=top width=113 height=13>Data do Docto</td>
        <td class=ct valign=top width=7 height=13><img height=13
                                                       src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                                                       width=1 border=0>
        </td>
        <td class=ct valign=top align="center" width=133 height=13>N&ordm;
            documento
        </td>
        <td class=ct valign=top width=7 height=13><img height=13
                                                       src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                                                       width=1 border=0>
        </td>
        <td class=ct valign=top align="center" width=62 height=13> Espécie Docto</td>
        <td class=ct valign=top width=7 height=13><img height=13
                                                       src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                                                       width=1 border=0>
        </td>
        <td class=ct valign=top align="center" width=34 height=13>Aceite</td>
        <td class=ct valign=top width=7 height=13>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
        <td class=ct valign=top align="center" width=102 height=13>Data Movto</td>
        <td class=ct valign=top width=7 height=13><img height=13
                                                       src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                                                       width=1 border=0>
        </td>

        <td class=ct valign=top width=178 height=13>Nosso número</td>

        <td class="cp" valign="top" width="7" height="13">
            <img height="13" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width="1" border="0">
        </td>
    </tr>
    <tr>
        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
        <td class=cp valign=top align="center" width=113 height=12>
            <div align=left>
                            <span class="campo">
                                <?php echo $this->dados->getBoleto()->getDataDocumento()->format("d/m/Y") ?>
                            </span>
            </div>
        </td>
        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
        <td class=cp valign=top align="center" width=133 height=12>
                        <span class="campo">
                            <?php echo $this->dados->getBoleto()->getNumeroDocumento() ?>
                        </span>
        </td>
        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
        <td class=cp valign=top align="center" width=62 height=12>
            <div align=left>
                            <span class="campo">
                                <?php echo $this->dados->getBanco()->getEspecieDoc() ?>
                            </span>
            </div>
        </td>
        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
        <td class=cp valign=top align="center" width=34 height=12>
            <div align=left>
                            <span class="campo">
                                <?php echo strtoupper(substr($this->dados->getBanco()->getAceite(), 0,1)) ?>
                            </span>
            </div>
        </td>
        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
        <td class=cp valign=top align="center" width=102 height=12>
            <div align=left>
                            <span class="campo">
                                <?php echo $this->dados->getBoleto()->getDataProcessamento()->format("d/m/Y") ?>
                            </span>
            </div>
        </td>
        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=cp valign=top align=right width=178 height=12>
            <span class="campo">
                <?php echo str_pad($this->dados->getBoleto()->getNossoNumero(),9,0,STR_PAD_LEFT) ?>
            </span>
        </td>

        <td class="cp" valign="top" width="7" height="12">
            <img height="12" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width="1" border="0">
        </td>
    </tr>
    <tr>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top width=113 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=113 border=0>
        </td>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top width=133 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=133 border=0>
        </td>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top width=62 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=62 border=0>
        </td>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top width=34 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=34 border=0>
        </td>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top width=102 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=102 border=0>
        </td>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top width=179 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=179 border=0>
        </td>
    </tr>
    </tbody>
</table>
<table cellspacing=0 cellpadding=0 border=0>
    <tbody>
    <tr>
        <td class=ct valign=top width=7 height=13><img height=13
                                                       src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                                                       width=1 border=0>
        </td>
        <td class=ct valign=top COLSPAN="3" height=13>Data da Oper</td>
        <td class=ct valign=top height=13 width=7><img height=13
                                                       src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                                                       width=1 border=0>
        </td>
        <td class=ct valign=top align="center" width=70 height=13>Carteira</td>
        <td class=ct valign=top height=13 width=7>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
        <td class=ct valign=top align="center" width=56 height=13>Espécie</td>
        <td class=ct valign=top height=13 width=7>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
        <td class=ct valign=top width=103 height=13>Quantidade</td>
        <td class=ct valign=top height=13 width=7>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
        <td class=ct valign=top width=102 height=13>Valor</td>
        <td class=ct valign=top width=7 height=13>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=ct valign=top width=178 height=13>(=) Valor documento</td>

        <td class="cp" valign="top" width="7" height="13">
            <img height="13" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width="1" border="0">
        </td>
    </tr>
    <tr>
        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
        <td valign=top align="center" class=cp height=12 COLSPAN="3">
            <div align=left>
                <?php echo $this->dados->getBoleto()->getDataProcessamento()->format("d/m/Y") ?>
            </div>
        </td>
        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
        <td class=cp valign=top align="center" width=70>
            <span class="campo">
                <?php echo $this->dados->getCedente()->getCarteira() ?>
            </span>
        </td>
        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
        <td class=cp valign=top align="center" width=56>
            <span class="campo">
                <?php echo $this->dados->getBanco()->getEspecie() ?>
            </span>
        </td>
        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
        <td class=cp valign=top width=103>
                        <span class="campo">
                            <?php echo $this->dados->getBoleto()->getQuantidade() ?>
                        </span>
        </td>
        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
        <td class=cp valign=top width=102>
                        <span class="campo">
                            <?php echo $this->dados->getBoleto()->getValorUnitario() ?>
                        </span>
        </td>
        <td class=cp valign=top width=7 height=12><img height=12
                                                       src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                                                       width=1 border=0>
        </td>

        <td class=cp valign=top align=right width=178 height=12>
            <span class="campo">
                <?php echo number_format($this->dados->getBoleto()->getValor() / 100, 2, ",", ".") ?>
            </span>
        </td>

        <td class="cp" valign="top" width="7" height="12">
            <img height="12" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width="1" border="0">
        </td>
    </tr>
    <tr>
        <td valign=top width=7 height=1><img height=1
                                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                                             width=7 border=0>
        </td>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=75 border=0>
        </td>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top width=31 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=31 border=0>
        </td>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top width=70 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=70 border=0>
        </td>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top width=56 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=56 border=0>
        </td>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top width=103 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=103 border=0>
        </td>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top width=102 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=102 border=0>
        </td>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>
        <td valign=top width=179 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=179 border=0>
        </td>
    </tr>
    </tbody>
</table>
<table cellspacing=0 cellpadding=0 width=666 border=0>
    <tbody>
    <tr>
        <td align=right width=10>
            <table cellspacing=0 cellpadding=0 border=0 align=left>
                <tbody>
                <tr>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                             width=1 border=0>
                    </td>
                </tr>
                <tr>
                    <td class=cp valign=top width=7 height=13>
                        <img height=13
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                             width=1 border=0>
                    </td>
                </tr>
                <tr>
                    <td valign=top width=7 height=1>
                        <img height=1
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                             width=1 border=0>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>

        <td class="sem-espacamento" valign=top style="width: 100%" rowspan=5>
            <font class=ct>Instruções (Todas as informações deste bloqueto são de exclusiva responsabilidade do
                Beneficiário)</font>
            <br>
            <br>
            <span class=cp> <FONT class=campo>
                                <?php echo $this->dados->getBoleto()->getInstrucoes1(); ?>
                                <br>
                                <?php echo $this->dados->getBoleto()->getInstrucoes2(); ?>
                                <br>
                                <?php echo $this->dados->getBoleto()->getInstrucoes3(); ?>
                                <br>
                                <?php echo $this->dados->getBoleto()->getInstrucoes4(); ?>
                            </FONT>
                            <br>
                        </span>
            <br>
            <span class=ct style="font: bold 12px Arial;">
                <!--* O não pagamento do título 10 dias após o vencimento implicará em protesto.-->
                <br>
                <br>
                <br>
            </span>
        </td>

        <td align=right width=178>
            <table cellspacing=0 cellpadding=0 border=0>
                <tbody>
                <tr>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                             width=1 border=0>
                    </td>

                    <td class=ct valign=top width=178 height=13>(-) Desconto / Abatimentos</td>

                    <td class="cp" valign="top" width="7" height="13">
                        <img height="13" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width="1" border="0">
                    </td>
                </tr>
                <tr>
                    <td class=cp valign=top width=7 height=13>
                        <img height=13
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                             width=1 border=0>
                    </td>
                    <td class=cp valign=top align=right width=178 height=12>
                    </td>

                    <td class="cp" valign="top" width="7" height="13">
                        <img height="13" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width="1" border="0">
                    </td>
                </tr>
                <tr>
                    <td valign=top width=7 height=1>
                        <img height=1
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                             width=7 border=0>
                    </td>
                    <td valign=top width=178 height=1>
                        <img height=1
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                             width=178 border=0>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>

    <tr>
        <td align=right width=10>
            <table cellspacing=0 cellpadding=0 border=0 align=left>
                <tbody>
                <tr>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                             width=1 border=0>
                    </td>
                </tr>
                <tr>
                    <td class=cp valign=top width=7 height=13>
                        <img height=13
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                             width=1 border=0>
                    </td>
                </tr>
                <tr>
                    <td valign=top width=7 height=1>
                        <img height=1
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                             width=1 border=0>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
        <td align=right width=188>
            <table cellspacing=0 cellpadding=0 border=0>
                <tbody>
                <tr>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                             width=1 border=0>
                    </td>

                    <td class=ct valign=top width=178 height=13>(-) Outras deduções</td>

                    <td class="cp" valign="top" width="7" height="13">
                        <img height="13" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width="1" border="0">
                    </td>
                </tr>
                <tr>
                    <td class=cp valign=top width=7 height=13><img height=13
                                                                   src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                                                                   width=1 border=0>
                    </td>

                    <td class=cp valign=top align=right width=178 height=12>
                    </td>

                    <td class="cp" valign="top" width="7" height="13">
                        <img height="13" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width="1" border="0">
                    </td>
                </tr>
                <tr>
                    <td valign=top width=7 height=1>
                        <img height=1
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                             width=7 border=0>
                    </td>
                    <td valign=top width=178 height=1>
                        <img height=1
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                             width=178 border=0>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    <tr>
        <td align=right width=10>
            <table cellspacing=0 cellpadding=0 border=0 align=left>
                <tbody>
                <tr>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                             width=1 border=0>
                    </td>
                </tr>
                <tr>
                    <td class=cp valign=top width=7 height=13>
                        <img height=13
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                             width=1 border=0>
                    </td>
                </tr>
                <tr>
                    <td valign=top width=7 height=1>
                        <img height=1
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                             width=1 border=0>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
        <td align=right width=188>
            <table cellspacing=0 cellpadding=0 border=0>
                <tbody>
                <tr>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                             width=1 border=0>
                    </td>
                    <td class=ct valign=top width=178 height=13>(+) Mora / Multa</td>

                    <td class="cp" valign="top" width="7" height="13">
                        <img height="13" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width="1" border="0">
                    </td>

                </tr>
                <tr>
                    <td class=cp valign=top width=7 height=13>
                        <img height=13
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                             width=1 border=0>
                    </td>

                    <td class=cp valign=top align=right width=178 height=12>
                    </td>

                    <td class="cp" valign="top" width="7" height="13">
                        <img height="13" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width="1" border="0">
                    </td>
                </tr>
                <tr>
                    <td valign=top width=7 height=1><img height=1
                                                         src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                                                         width=7 border=0>
                    </td>
                    <td valign=top width=178 height=1>
                        <img height=1
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                             width=178 border=0>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    <tr>
        <td align=right width=10>
            <table cellspacing=0 cellpadding=0 border=0 align=left>
                <tbody>
                <tr>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                             width=1 border=0>
                    </td>
                </tr>
                <tr>
                    <td class=cp valign=top width=7 height=13>
                        <img height=13
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                             width=1 border=0>
                    </td>
                </tr>
                <tr>
                    <td valign=top width=7 height=1>
                        <img height=1
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                             width=1 border=0>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>

        <td align=right width=188>
            <table cellspacing=0 cellpadding=0 border=0>
                <tbody>
                <tr>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                             width=1 border=0>
                    </td>

                    <td class=ct valign=top width=178 height=13>(+) Outros acréscimos</td>

                    <td class="cp" valign="top" width="7" height="13">
                        <img height="13" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width="1" border="0">
                    </td>
                </tr>
                <tr>
                    <td class=cp valign=top width=7 height=13>
                        <img height=13
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                             width=1 border=0>
                    </td>

                    <td class=cp valign=top align=right width=178 height=12>
                    </td>

                    <td class="cp" valign="top" width="7" height="13">
                        <img height="13" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width="1" border="0">
                    </td>
                </tr>
                <tr>
                    <td valign=top width=7 height=1>
                        <img height=1
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                             width=7 border=0>
                    </td>
                    <td valign=top width=178 height=1>
                        <img height=1
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                             width=178 border=0>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>

    <tr>
        <td align=right width=10>
            <table cellspacing=0 cellpadding=0 border=0 align=left>
                <tbody>
                <tr>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                             width=1 border=0>
                    </td>
                </tr>
                <tr>
                    <td class=cp valign=top width=7 height=13>
                        <img height=13
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                             width=1 border=0>
                    </td>
                </tr>
                <tr>
                    <td valign=top width=7 height=1>
                        <img height=1
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                             width=1 border=0>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>

        <td align=right width=188>
            <table cellspacing=0 cellpadding=0 border=0>
                <tbody>
                <tr>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                             width=1 border=0>
                    </td>

                    <td class=ct valign=top width=178 height=13>(=) Valor cobrado</td>

                    <td class="cp" valign="top" width="7" height="13">
                        <img height="13" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width="1" border="0">
                    </td>
                </tr>
                <tr>
                    <td class=cp valign=top width=7 height=13>
                        <img height=13
                             src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                             width=1 border=0>
                    </td>

                    <td class=cp valign=top align=right width=178 height=12>
                    </td>

                    <td class="cp" valign="top" width="7" height="13">
                        <img height="13" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width="1" border="0">
                    </td>
                </tr>
                <tr>
                    <td valign=top width=7 height=1>
                        <img height=1
                             width=7 border=0>
                    </td>
                    <td valign=top width=178 height=1>
                        <img height=1
                             width=178 border=0>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>

    </tbody>
</table>
<table cellspacing=0 cellpadding=0 width=666 border=0>
    <tbody>
    <tr>
        <td valign=top width=666 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=666 border=0>
        </td>
    </tr>
    </tbody>
</table>

<!--PAGADOR-->
<table cellspacing=0 cellpadding=0 border=0>
    <tbody>
    <tr>
        <td class=ct valign=top width=7 height=13>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
        <td class=ct valign=top width=100 height=13>Pagador</td>

        <td class=cp valign=top width=558 height=12>
            <span class="campo">
                <?php echo $this->dados->getSacado()->getNome() . ' - ' . $this->dados->getSacado()->getDocumento() ?>
            </span>
        </td>

        <td class=ct valign=top width=7 height=13>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
    </tr>
    </tbody>
</table>
<!--PAGADOR-->


<!--ENDEREÇO-->
<table cellspacing=0 cellpadding=0 border=0>
    <tbody>
    <tr>
        <td class=cp valign=top width=7 height=12>
            <img height=12
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=ct valign=top width=100 height=13>Endereço</td>

        <td class=cp valign=top width=558 height=12>
            <span class="campo">
                <?php echo $this->dados->getSacado()->getEndereco1() .' - '. $this->dados->getSacado()->getEndereco2() ?>
            </span>
        </td>

        <td class=ct valign=top width=7 height=13>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
    </tr>
    </tbody>
</table>
<!--ENDEREÇO-->


<!--SACADOR-->
<table cellspacing=0 cellpadding=0 border=0>
    <tbody>
    <tr>
        <td class=ct valign=top width=7 height=13>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>

        <td class=ct width=658>Sacador/Avalista</td>

        <td class=ct valign=top width=7 height=13>
            <img height=13
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                 width=1 border=0>
        </td>
    </tr>
    <tr>
        <td valign=top width=7 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=7 border=0>
        </td>

        <td valign=top width=658 height=1>
            <img height=1
                 src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==
                 width=658 border=0>
        </td>
    </tr>
    </tbody>
</table>
<!--SACADOR-->


<!--CÓDIGO DE BARRAS-->
<TABLE cellSpacing=0 cellPadding=0 width=666 border=0>
    <tbody>
    <tr>
        <td class=ct valign=top width=7 height=55>
        </td>

        <td vAlign=bottom align=left width="472" height=50>
            <img src="<?php echo $this->dados->getBoleto()->getCodigoDeBarras()->render(); ?>"/>
        </td>

        <td class=ct valign=center align="center" width=180 height=13 style="FONT: 9px Arial Narrow";">
            Autenticação Mecânica
            <br>
            <img height="1"
                 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg=="
                 width="180" border="0">
            <br>
            <span style="FONT: bold 9px Arial Narrow";">FICHA DE COMPENSAÇÃO</span>
        </td>
    </tr>
    </tbody>
</table>
<!--CÓDIGO DE BARRAS-->

</body>
</html>
