<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.0 Transitional//EN'>
<html>
<head>
    <title>
        <?php echo $this->dados->getCedente()->getIdentificacao(); ?>
    </title>
    <meta http-equiv=Content-Type content=text/html charset=utf-8/>
    <meta name="Generator" content="Projeto BoletoPHP - www.boletophp.com.br - Licença GPL"/>
    <style type=text/css>
        .cp {
            font: bold 10px Arial;
            color: black;
            padding-left: 5px;
        }

        .cp2 {
            font: bold 10px Arial;
            color: black;
            padding-left: 5px;
            padding-bottom: 2px;
            border-left: 2px solid black;
        }

        .ti {
            font: 9px Arial, Helvetica, sans-serif;
            padding: 0px;
        }

        .ld {
            font: bold 15px Arial;
            color: #000000;
            padding: 0px;
        }

        .ct {
            FONT: 9px "Arial Narrow";
            COLOR: #000033;
            padding-left: 5px;
        }

        .ct2 {
            FONT: 9px "Arial Narrow";
            COLOR: #000033;
            padding-left: 5px;
            padding-bottom: 2px;
            border-left: 2px solid black;
        }

        .cn {
            FONT: 9px Arial;
            COLOR: black;
            padding: 0px;
        }

        .ld2 {
            font: bold 12px Arial;
            color: #000000;
            padding: 0px;
        }

        @media print {
            .no-print{
                display: none;
            }
        }
    </style>
</head>

<body text="#000000" bgColor="#ffffff" topMargin=0 rightMargin=0>
    <?php
    $linha_horizontal = "
        <tbody>
            <tr>
                <td valign=top colspan=20>
                    <img height=1
                        src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg=='
                        width='100%' border=0>
                </td>
            </tr>
        </tbody>
    ";    
    ?>

    <table width="100%" cellspacing=0 cellpadding=0 border=0 class="no-print">
        <tr>
            <td valign="top" class="cp">
                <div style="text-align: center;">Instruções de Impressão</div>
            </td>
        </tr>
        <tr>
            <td valign=top class="cp">
                <div style="text-align: left;"><p>
                    Imprima em impressora jato de tinta (ink jet) ou laser em qualidade normal ou alta (Não use modo
                    econômico).<br>
                    Utilize folha A4 (210 x 297 mm) ou Carta (216 x 279 mm) e margens mínimas à esquerda e à direita do
                    formulário.<br>
                    Corte na linha indicada. Não rasure, risque, fure ou dobre a região onde se encontra o Código de
                    barras.<br>
                    Caso não apareça o Código de barras no final, clique em F5 para atualizar esta tela.
                    Caso tenha problemas ao imprimir, copie a sequencia numérica abaixo e pague no caixa eletrônico ou
                    no internet banking:<br>
                    <br>
                    <span class="ld2">&nbsp;&nbsp;&nbsp;&nbsp;Linha Digitável: &nbsp;<img
                            src="<?php echo $this->dados->getBoleto()->getLinhaDigitavel('base64')->render() ?>"/><br>
                        &nbsp;&nbsp;&nbsp;&nbsp;Valor: &nbsp;&nbsp;R$ <?php echo number_format($this->dados->getBoleto()->getValor() / 100, 2, ',', '.') ?>
                        <br>
                    </span>
                </div>
            </td>
        </tr>
    </table>
    <br>

    <table cellspacing=0 cellpadding=0 width="100%" border=0>
        <tbody>
        <tr>
            <td class="ct" width="100%">
                <img height=1
                    src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAApkAAAACAQAAAAA76vpWAAAAGUlEQVR42mNgbDiQYCDBw8ZMPUYDAy0MBQCvGyXfT4/GUQAAAABJRU5ErkJggg=="
                    width="100%" border="0">
            </td>
        </tr>
        <tr>
            <td class="ct" width="100%">
                <div style="text-align: right;">
                    <b class="cp">Recibo do Pagador</b>
                </div>
            </td>
        </tr>
        </tbody>
    </table>

    <table width="100%" cellspacing=5 cellpadding=0 border=0>
        <tr>
            <td width="100%">
            </td>
        </tr>
    </table>

    <table width="100%" cellspacing=5 cellpadding=0 border=0 align=Default>
        <tr>
            <td width="10%">
                <img src="<?php echo $this->dados->getCedente()->getLogoCedente() ?>"
                    style="max-width: 200px;max-height: 60px;"/>
            </td>
            <td class="ti"
                width="70%"><?php echo $this->dados->getCedente()->getIdentificacao(); ?> <?php echo ($this->dados->getCedente()->getDocumento())
                    ? "<br>" . $this->dados->getCedente()->getDocumento() : '' ?>
                <br>
            </td>
            <td style="text-align: right;" width="20%" class="ti">&nbsp;</td>
        </tr>
    </table>
    <BR>

    <table cellspacing=0 cellpadding=0 width="100%" border=0>
        <tr>
            <td class="cp" colspan="3">
                <span class="campo">
                    <IMG src="<?php echo $this->dados->getBanco()->getLogoBanco() ?>" width="150" height="40"
                        border=0>
                </span>
            </td>
            <td valign="bottom">
                <img height=22
                    src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAATAQMAAACA8k5ZAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                    width=1 border=0>
            </td>
            <td class=cpt colspan="4" valign=bottom>
                <div style="text-align: center;">
                    <font class=bc>
                        <?php echo $this->dados->getBanco()->getCodigoBanco(), '-', $this->dados->getBanco()->getCodigoBancoDv() ?>
                    </font>
                </div>
            </td>
            <td valign=bottom>
                <img height=22
                    src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAATAQMAAACA8k5ZAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                    width=1 border=0>
            </td>
            <td class="ld" style="text-align: right;" colspan="11" valign=bottom>
                <span class="ld"> 
                    <span class="campotitulo">
                        <img src="<?php echo $this->dados->getBoleto()->getLinhaDigitavel('base64')->render() ?>"/>
                    </span>
                </span>
            </td>
        </tr>
        <?= $linha_horizontal ?>
    </table>

    <!--Beneficiario-->
    <table cellspacing=0 cellpadding=0 border=0 width="100%">
        <tr>
            <td class="ct2" valign=top colspan=7>Beneficiário</td>
            <td class="ct2" valign=top colspan=4>Agência/Código do Beneficiário</td>
            <td class="ct2" valign=top colspan=2>Espécie</td>
            <td class="ct2" valign=top colspan=2>Quantidade</td>
            <td class="ct2" valign=top colspan=5>Nosso número</td>
        </tr>
        <tr>
            <td class=cp2 valign=top colspan=7>
                <span class="campo">
                    <?php echo $this->dados->getCedente()->getNomeCedente(); ?>
                </span>
            </td>
            <td class=cp2 valign=top colspan=4>
                <span class="campo">
                    <?php echo $this->dados->getCedente()->getAgenciaCodigo() ?>
                </span>
            </td>
            <td class=cp2 valign=top colspan=2>
                <span class="campo">
                    <?php echo $this->dados->getBanco()->getEspecie() ?>
                </span>
            </td>
            <td class=cp2 valign=top colspan=2>
                <span class="campo">
                    <?php echo $this->dados->getBoleto()->getQuantidade() ?>
                </span>
            </td>
            <td class=cp2 valign=top style="text-align: right;" colspan=5>
                <span class="campo">
                    <?php echo $this->dados->getBoleto()->getNossoNumeroFormatado() ?>
                </span>
            </td>
        </tr>
        <?= $linha_horizontal ?>
    </table>

    <!--ENDEREÇO-->
    <table cellspacing=0 cellpadding=0 border=0 width="100%">
        <tr>
            <td class=ct2 valign=top colspan=12>Endereço</td>
            <td class=ct2 valign=top colspan=3>UF</td>
            <td class=ct2 valign=top colspan=5>CEP</td>
        </tr>
        <tr>
            <td class=cp2 valign=top colspan=12>
                <span class="campo">
                    <?php echo $this->dados->getCedente()->getEnderecoFormatado() ?>
                </span>
            </td>
            <td class=cp2 valign=top colspan=3>
                <span class="campo">
                    <?php echo $this->dados->getCedente()->getUf() ?>
                </span>
            </td>
            <td class=cp2 valign=top style="text-align: right;" colspan=5>
                <span class="campo">
                    <?php echo $this->dados->getCedente()->getCep() ?>
                </span>
            </td>
        </tr>
        <?= $linha_horizontal ?>
    </table>

    <!--NÚMERO DO DOCUMENTO-->
    <table cellspacing=0 cellpadding=0 border=0 width="100%">
        <tr>
            <td class=ct2 valign=top colspan=5>Número do documento</td>
            <td class=ct2 valign=top colspan=5>CPF/CNPJ</td>
            <td class=ct2 valign=top colspan=5>Vencimento</td>
            <td class=ct2 valign=top colspan=5>Valor documento</td>
        </tr>
        <tr>
            <td class=cp2 valign=top colspan=5>
                <span class="campo">
                    <?php echo $this->dados->getBoleto()->getNumeroDocumento() ?>
                </span>
            </td>
            <td class=cp2 valign=top colspan=5>
                <span class="campo">
                    <?php echo $this->dados->getCedente()->getDocumento() ?>
                </span>
            </td>
            <td class=cp2 valign=top colspan=5>
                <span class="campo">
                    <?php echo ($this->dados->getBoleto()->getDataVencimento())
                        ? $this->dados->getBoleto()->getDataVencimento()->format('d/m/Y')
                        : "Contra Apresentação" ?>
                </span>
            </td>
            <td class=cp2 valign=top style="text-align: right;" colspan=5>
                <span class="campo">
                    <?php echo number_format($this->dados->getBoleto()->getValor() / 100, 2, ",", ".") ?>
                </span>
            </td>
        </tr>
        <?= $linha_horizontal ?>
    </table>

    <!--(-) Desconto / Abatimentos-->
    <table cellspacing=0 cellpadding=0 border=0 width="100%">
        <tr>
            <td class=ct2 valign=top colspan=4>(-) Desconto / Abatimentos</td>
            <td class=ct2 valign=top colspan=4>(-) Outras deduções</td>
            <td class=ct2 valign=top colspan=4>(+) Mora / Multa</td>
            <td class=ct2 valign=top colspan=4>(+) Outros acréscimos</td>
            <td class=ct2 valign=top colspan=4>(=) Valor cobrado</td>
        </tr>
        <tr>
            <td class=cp2 valign=top colspan=4 style="text-align: right;" height=15></td>
            <td class=cp2 valign=top colspan=4 style="text-align: right;" height=15></td>
            <td class=cp2 valign=top colspan=4 style="text-align: right;" height=15></td>
            <td class=cp2 valign=top colspan=4 style="text-align: right;" height=15></td>
            <td class=cp2 valign=top colspan=4 style="text-align: right;" height=15></td>
        </tr>
        <?= $linha_horizontal ?>
    </table>

    <!--PAGADOR-->
    <table cellspacing=0 cellpadding=0 border=0 width="100%">
        <tr>
            <td class=ct2 valign=top colspan=20>Pagador</td>
        </tr>
        <tr>
            <td class=cp2 valign=top colspan=20>
                <span class="campo">
                    <?php
                    if ($this->dados->getSacado()->getDocumento()) {
                        $l = preg_replace("/[^\d]/", "", $this->dados->getSacado()->getDocumento());
                        if (strlen($l) == 11) {
                            $documento = 'CPF: ';
                        } else {
                            $documento = 'CNPJ: ';
                        }
                    } else {
                        $documento = '';
                    }
                    ?>
                    <?php echo $this->dados->getSacado()->getNome() . ' - ' . $documento . $this->dados->getSacado()->getDocumento() ?>
                </span>
                <br>
                <span>
                    <?php echo $this->dados->getSacado()->getEndereco1() ?>
                </span>
                <br>
                <span>
                    <?php echo $this->dados->getSacado()->getEndereco2() ?>
                </span>
            </td>
        </tr>
        <?= $linha_horizontal ?>
    </table>

    <!--SAC-->
    <table cellspacing=0 cellpadding=0 border=0 width="100%">
        <tr>
            <td class=cp2 valign=top colspan=20>
                <span class="campo">SAC CAIXA: 0800 726 0101 (informações, reclamações, sugestões e elogios)</span><br>
                <span class="campo"> Para pessoas com deficiência auditiva ou de fala: 0800 726 2492</span><br>
                <span class="campo"> Ouvidoria: 0800 725 7474</span><br>
                <span class="campo"> www.caixa.gov.br</span>
            </td>
        </tr>
        <?= $linha_horizontal ?>
    </table>

    <table cellspacing=0 cellpadding=0 border=0 width="100%">
        <tr>
            <td class=ct colspan=10>Demonstrativo</td>
            <td class=ct colspan=10 style="text-align: right;">Autenticação mecânica</td>
        </tr>
        <tr>
            <td class=cp colspan=20>
                <span class="campo">
                    <?php echo $this->dados->getBoleto()->getDemonstrativo1() ?>
                    <br>
                    <?php echo $this->dados->getBoleto()->getDemonstrativo2() ?>
                    <br>
                    <?php echo $this->dados->getBoleto()->getDemonstrativo3() ?>
                    <br>
                </span>
            </td>
        </tr>
    </table>

    <br>
    <br>

    <table cellspacing=0 cellpadding=0 width="100%" border=0>
        <tr>
            <td class=ct width="100%">
            </td>
        </tr>
        <tbody>
        <tr>
            <td class=ct width="100%">
                <div style="text-align: right;">Corte na linha pontilhada</div>
            </td>
        </tr>
        <tr>
            <td class=ct width="100%">
                <img height=1
                    src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAApkAAAACAQAAAAA76vpWAAAAGUlEQVR42mNgbDiQYCDBw8ZMPUYDAy0MBQCvGyXfT4/GUQAAAABJRU5ErkJggg=="
                    width="100%" border=0>
            </td>
        </tr>
        </tbody>
    </table>
    <br>

    <table cellspacing=0 cellpadding=0 width="100%" border=0>
        <tr>
            <td class="cp" colspan="3">
                <span class="campo">
                    <IMG src="<?php echo $this->dados->getBanco()->getLogoBanco() ?>" width="150" height="40"
                            border=0>
                </span>
            </td>
            <td valign="bottom">
                <img height=22
                    src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAATAQMAAACA8k5ZAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                    width=1 border=0>
            </td>
            <td class=cpt colspan="4" valign=bottom>
                <div style="text-align: center;">
                    <font class=bc>
                        <?php echo $this->dados->getBanco()->getCodigoBanco(), '-', $this->dados->getBanco()->getCodigoBancoDv() ?>
                    </font>
                </div>
            </td>
            <td valign=bottom>
                <img height=22
                    src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAATAQMAAACA8k5ZAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC
                    width=1 border=0>
            </td>
            <td class="ld" style="text-align: right;" colspan="11" valign=bottom>
                <span class="ld"> 
                    <span class="campotitulo">
                        <img src="<?php echo $this->dados->getBoleto()->getLinhaDigitavel('base64')->render() ?>"/>
                    </span>
                </span>
            </td>
        </tr>
        <?= $linha_horizontal ?>
    </table>

    <!--LOCAL DE PAGAMENTO-->
    <table cellspacing=0 cellpadding=0 border=0 width="100%">
        <tr>
            <td class=ct2 valign=top colspan=15>Local de pagamento</td>
            <td class=ct2 valign=top colspan=5>Vencimento</td>
        </tr>
        <tr>
            <td class=cp2 valign=top colspan=15>
                PREFERENCIALMENTE NAS CASAS LOTÉRICAS ATÉ O VALOR LIMITE
            </td>
            <td class=cp2 valign=bottom style="text-align: right;" colspan=5>
                <span class="campo">
                    <?php echo ($this->dados->getBoleto()->getDataVencimento())
                        ? $this->dados->getBoleto()->getDataVencimento()->format("d/m/Y")
                        : "Contra Apresentação" ?>
                </span>
            </td>
        </tr>
        <?= $linha_horizontal ?>
    </table>

    <!--BENEFICIARIO-->
    <table cellspacing=0 cellpadding=0 border=0 width="100%">
        <tr>
            <td class=ct2 valign=top colspan=12>Beneficiário</td>
            <td class=ct2 valign=top colspan=3>CPF/CNPJ</td>
            <td class=ct2 valign=top colspan=5>Agência/Código Beneficiário</td>
        </tr>
        <tr>
            <td class=cp2 valign=top colspan=12>
                <span class="campo">
                    <?php echo $this->dados->getCedente()->getNomeCedente() ?>
                </span>
            </td>
            <td class=cp2 valign=top colspan=3>
                <span class="campo">
                    <?php echo $this->dados->getCedente()->getDocumento() ?>
                </span>
            </td>
            <td class=cp2 valign=top style="text-align: right;" colspan=5>
                <span class="campo">
                    <?php echo $this->dados->getCedente()->getAgenciaCodigo() ?>
                </span>
            </td>
        </tr>
        <?= $linha_horizontal ?>
    </table>

    <!--ENDEREÇO-->
    <table cellspacing=0 cellpadding=0 border=0 width="100%">
        <tr>
            <td class=ct2 valign=top colspan=13>Endereço</td>
            <td class=ct2 valign=top colspan=2>UF</td>
            <td class=ct2 valign=top colspan=5>CEP</td>
        </tr>
        <tr>
            <td class=cp2 valign=top colspan=13>
                <span class="campo">
                    <?php echo $this->dados->getCedente()->getEnderecoFormatado() ?>
                </span>
            </td>
            <td class=cp2 valign=top colspan=2>
                <span class="campo">
                    <?php echo $this->dados->getCedente()->getUf() ?>
                </span>
            </td>
            <td class=cp2 valign=top style="text-align: right;" colspan=5>
                <span class="campo">
                    <?php echo $this->dados->getCedente()->getCep() ?>
                </span>
            </td>
        </tr>
        <?= $linha_horizontal ?>
    </table>

    <!--DATA DO DOCUMENTO-->
    <table cellspacing=0 cellpadding=0 border=0 width="100%">
        <tr>
            <td class=ct2 valign=top colspan=3>Data do documento</td>
            <td class=ct2 valign=top colspan=3>N&ordm;documento</td>
            <td class=ct2 valign=top colspan=3>Espécie doc.</td>
            <td class=ct2 valign=top colspan=3>Aceite</td>
            <td class=ct2 valign=top colspan=3>Data processamento</td>
            <td class=ct2 valign=top colspan=5>Nosso número</td>
        </tr>
        <tr>
            <td class=cp2 valign=top colspan=3>
                <div align=left>
                    <span class="campo">
                        <?php echo $this->dados->getBoleto()->getDataDocumento()->format("d/m/Y") ?>
                    </span>
                </div>
            </td>
            <td class=cp2 valign=top colspan=3>
                <span class="campo">
                    <?php echo $this->dados->getBoleto()->getNumeroDocumento() ?>
                </span>
            </td>
            <td class=cp2 valign=top colspan=3>
                <div align=left>
                    <span class="campo">
                        <?php echo $this->dados->getBanco()->getEspecieDoc() ?>
                    </span>
                </div>
            </td>
            <td class=cp2 valign=top colspan=3>
                <div align=left>
                    <span class="campo">
                        <?php echo $this->dados->getBanco()->getAceite() ?>
                    </span>
                </div>
            </td>
            <td class=cp2 valign=top colspan=3>
                <div align=left>
                    <span class="campo">
                        <?php echo $this->dados->getBoleto()->getDataProcessamento()->format("d/m/Y") ?>
                    </span>
                </div>
            </td>
            <td class=cp2 valign=top style="text-align: right;" colspan=5>
                <span class="campo">
                    <?php echo $this->dados->getBoleto()->getNossoNumeroFormatado() ?>
                </span>
            </td>
        </tr>
        <?= $linha_horizontal ?>
    </table>

    <!--USO DO BANCO-->
    <table cellspacing=0 cellpadding=0 border=0 width="100%">
        <tr>
            <td class=ct2 valign=top colspan=3>Uso do banco</td>
            <td class=ct2 valign=top colspan=3>Carteira</td>
            <td class=ct2 valign=top colspan=3>Espécie</td>
            <td class=ct2 valign=top colspan=3>Quantidade</td>
            <td class=ct2 valign=top colspan=3>Valor Documento</td>
            <td class=ct2 valign=top colspan=5>(=) Valor documento</td>
        </tr>
        <tr>
            <td class=cp2 valign=top colspan=3>
                <div align=left>
                </div>
            </td>
            <td class=cp2 valign=top colspan=3>
                <div align=left> 
                    <span class="campo">
                        <?php echo $this->dados->getCedente()->getDescricaoCarteira() ?>
                    </span>
                </div>
            </td>
            <td class=cp2 valign=top colspan=3>
                <div align=left>
                    <span class="campo">
                        <?php echo $this->dados->getBanco()->getEspecie() ?>
                    </span>
                </div>
            </td>
            <td class=cp2 valign=top colspan=3>
                <span class="campo">
                    <?php echo $this->dados->getBoleto()->getQuantidade() ?>
                </span>
            </td>
            <td class=cp2 valign=top colspan=3>
                <span class="campo">
                    <?php echo $this->dados->getBoleto()->getValorUnitario() ?>
                </span>
            </td>
            <td class=cp2 valign=top style="text-align: right;" colspan=5>
                <span class="campo">
                    <?php echo number_format($this->dados->getBoleto()->getValor() / 100, 2, ",", ".") ?>
                </span>
            </td>
        </tr>
        <?= $linha_horizontal ?>
    </table>

    <!--INSTRUÇÕES-->
    <table cellspacing=0 cellpadding=0 width="100%" border=0>
        <tr>
            <td class=ct2 valign=top colspan=15 rowspan=5>
                <font class=ct>Instruções (Texto de responsabilidade do beneficiário)</font>
                <br>
                <br>
                <span class=cp> <FONT class=campo>
                        <?php echo $this->dados->getBoleto()->getInstrucoes1(); ?>
                        <br>
                        <?php echo $this->dados->getBoleto()->getInstrucoes2(); ?>
                        <br>
                        <?php echo $this->dados->getBoleto()->getInstrucoes3(); ?>
                        <br>
                        <?php echo $this->dados->getBoleto()->getInstrucoes4(); ?>
                    </FONT>
                    <br>
                    <br> 
                </span>
            </td>
            <td class=ct2 valign=top colspan=5 height=15 style="border-bottom: 1px solid black;">(-) Desconto / Abatimentos</td>
        </tr>
        <tr>
            <td class=ct2 valign=top colspan=5 height=15 style="border-bottom: 1px solid black;">(-) Outras deduções</td>
        </tr>
        <tr>
            <td class=ct2 valign=top colspan=5 height=15 style="border-bottom: 1px solid black;">(+) Mora / Multa</td>
        </tr>
        <tr>
            <td class=ct2 valign=top colspan=5 height=15 style="border-bottom: 1px solid black;">(+) Outros acréscimos</td>
        </tr>
        <tr>
            <td class=ct2 valign=top colspan=5 height=15 style="border-bottom: 1px solid black;">(=) Valor cobrado</td>
        </tr>
        <?= $linha_horizontal ?>
    </table>

    <!--PAGADOR-->
    <table cellspacing=0 cellpadding=0 border=0 width="100%">
        <tr>
            <td class=ct2 valign=top colspan=20>Pagador</td>
        </tr>
        <tr>
            <td class=cp2 valign=top colspan=20>
                <span class="campo">
                    <?php
                    if ($this->dados->getSacado()->getDocumento()) {
                        $l = preg_replace("/[^\d]/", "", $this->dados->getSacado()->getDocumento());
                        if (strlen($l) == 11) {
                            $documento = 'CPF: ';
                        } else {
                            $documento = 'CNPJ: ';
                        }
                    } else {
                        $documento = '';
                    }
                    ?>
                    <?php echo $this->dados->getSacado()->getNome() . ' - ' . $documento . $this->dados->getSacado()->getDocumento() ?>
                </span>
            </td>
        </tr>
        <tr>
            <td class=cp2 valign=top colspan=20>
                <span class="campo">
                    <?php echo $this->dados->getSacado()->getEndereco1() ?>
                </span>
            </td>
        </tr>
        <tr>
            <td class=cp2 valign=top colspan=15>
                <span class="campo">
                    <?php echo $this->dados->getSacado()->getEndereco2() ?>
                </span>
            </td>
            <td class=ct2 valign=top colspan=5>Cód. baixa</td>
        </tr>
        <?= $linha_horizontal ?>
    </table>

    <!--SAC-->
    <table cellspacing=0 cellpadding=0 border=0 width="100%">
        <tr>
            <td class=cp2 valign=top colspan=20>
                <span class="campo">SAC CAIXA: 0800 726 0101 (informações, reclamações, sugestões e elogios)</span><br>
                <span class="campo"> Para pessoas com deficiência auditiva ou de fala: 0800 726 2492</span><br>
                <span class="campo"> Ouvidoria: 0800 725 7474</span><br>
                <span class="campo"> www.caixa.gov.br</span>
            </td>
        </tr>
        <?= $linha_horizontal ?>
    </table>
    <!--FIM SAC-->

    <table cellSpacing=0 cellPadding=0 border=0 width="100%">
        <tr>
            <td class=ct colspan=10>Sacador/Avalista</td>
            <td class=ct colspan=10>
                <div style="text-align: right;">Autenticação mecânica - <b class=cp>Ficha de Compensação</b>
                </div>
            </td>
        </tr>
    </table>

    <table cellSpacing=0 cellPadding=0 width="100%" border=0>
        <tbody>
        <tr>
            <td vAlign=bottom align=left height=50>
                <img src="<?php echo $this->dados->getBoleto()->getCodigoDeBarras()->render(); ?>"/>
            </td>
        </tr>
        </tbody>
    </table>

    <table cellSpacing=0 cellPadding=0 width="100%" border=0>
        <tr>
            <td class=ct width="100%">
            </td>
        </tr>
        <tbody>
        <tr>
            <td class=ct width="100%">
                <div style="text-align: right;">Corte na linha pontilhada</div>
            </td>
        </tr>
        <tr>
            <td class=ct width="100%">
                <img height=1
                    src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAApkAAAACAQAAAAA76vpWAAAAGUlEQVR42mNgbDiQYCDBw8ZMPUYDAy0MBQCvGyXfT4/GUQAAAABJRU5ErkJggg=="
                    width="100%" border=0>
            </td>
        </tr>
        </tbody>
    </table>

</body>
</html>
